/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!


goog.provide('proto.jspb.test.Proto3Enum');
goog.provide('proto.jspb.test.TestProto3');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.jspb.test.ForeignMessage');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.jspb.test.TestProto3 = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.jspb.test.TestProto3.repeatedFields_, proto.jspb.test.TestProto3.oneofGroups_);
};
goog.inherits(proto.jspb.test.TestProto3, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.jspb.test.TestProto3.displayName = 'proto.jspb.test.TestProto3';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.jspb.test.TestProto3.repeatedFields_ = [31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,49,52];

/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.jspb.test.TestProto3.oneofGroups_ = [[111,112,113,114]];

/**
 * @enum {number}
 */
proto.jspb.test.TestProto3.OneofFieldCase = {
  ONEOF_FIELD_NOT_SET: 0,
  ONEOF_UINT32: 111,
  ONEOF_FOREIGN_MESSAGE: 112,
  ONEOF_STRING: 113,
  ONEOF_BYTES: 114
};

/**
 * @return {proto.jspb.test.TestProto3.OneofFieldCase}
 */
proto.jspb.test.TestProto3.prototype.getOneofFieldCase = function() {
  return /** @type {proto.jspb.test.TestProto3.OneofFieldCase} */(jspb.Message.computeOneofCase(this, proto.jspb.test.TestProto3.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.jspb.test.TestProto3.prototype.toObject = function(opt_includeInstance) {
  return proto.jspb.test.TestProto3.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.jspb.test.TestProto3} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jspb.test.TestProto3.toObject = function(includeInstance, msg) {
  var f, obj = {
    optionalInt32: jspb.Message.getFieldWithDefault(msg, 1, 0),
    optionalInt64: jspb.Message.getFieldWithDefault(msg, 2, 0),
    optionalUint32: jspb.Message.getFieldWithDefault(msg, 3, 0),
    optionalUint64: jspb.Message.getFieldWithDefault(msg, 4, 0),
    optionalSint32: jspb.Message.getFieldWithDefault(msg, 5, 0),
    optionalSint64: jspb.Message.getFieldWithDefault(msg, 6, 0),
    optionalFixed32: jspb.Message.getFieldWithDefault(msg, 7, 0),
    optionalFixed64: jspb.Message.getFieldWithDefault(msg, 8, 0),
    optionalSfixed32: jspb.Message.getFieldWithDefault(msg, 9, 0),
    optionalSfixed64: jspb.Message.getFieldWithDefault(msg, 10, 0),
    optionalFloat: +jspb.Message.getFieldWithDefault(msg, 11, 0.0),
    optionalDouble: +jspb.Message.getFieldWithDefault(msg, 12, 0.0),
    optionalBool: jspb.Message.getFieldWithDefault(msg, 13, false),
    optionalString: jspb.Message.getFieldWithDefault(msg, 14, ""),
    optionalBytes: msg.getOptionalBytes_asB64(),
    optionalForeignMessage: (f = msg.getOptionalForeignMessage()) && proto.jspb.test.ForeignMessage.toObject(includeInstance, f),
    optionalForeignEnum: jspb.Message.getFieldWithDefault(msg, 22, 0),
    repeatedInt32List: jspb.Message.getRepeatedField(msg, 31),
    repeatedInt64List: jspb.Message.getRepeatedField(msg, 32),
    repeatedUint32List: jspb.Message.getRepeatedField(msg, 33),
    repeatedUint64List: jspb.Message.getRepeatedField(msg, 34),
    repeatedSint32List: jspb.Message.getRepeatedField(msg, 35),
    repeatedSint64List: jspb.Message.getRepeatedField(msg, 36),
    repeatedFixed32List: jspb.Message.getRepeatedField(msg, 37),
    repeatedFixed64List: jspb.Message.getRepeatedField(msg, 38),
    repeatedSfixed32List: jspb.Message.getRepeatedField(msg, 39),
    repeatedSfixed64List: jspb.Message.getRepeatedField(msg, 40),
    repeatedFloatList: jspb.Message.getRepeatedFloatingPointField(msg, 41),
    repeatedDoubleList: jspb.Message.getRepeatedFloatingPointField(msg, 42),
    repeatedBoolList: jspb.Message.getRepeatedField(msg, 43),
    repeatedStringList: jspb.Message.getRepeatedField(msg, 44),
    repeatedBytesList: msg.getRepeatedBytesList_asB64(),
    repeatedForeignMessageList: jspb.Message.toObjectList(msg.getRepeatedForeignMessageList(),
    proto.jspb.test.ForeignMessage.toObject, includeInstance),
    repeatedForeignEnumList: jspb.Message.getRepeatedField(msg, 52),
    oneofUint32: jspb.Message.getFieldWithDefault(msg, 111, 0),
    oneofForeignMessage: (f = msg.getOneofForeignMessage()) && proto.jspb.test.ForeignMessage.toObject(includeInstance, f),
    oneofString: jspb.Message.getFieldWithDefault(msg, 113, ""),
    oneofBytes: msg.getOneofBytes_asB64()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.jspb.test.TestProto3}
 */
proto.jspb.test.TestProto3.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.jspb.test.TestProto3;
  return proto.jspb.test.TestProto3.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.jspb.test.TestProto3} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.jspb.test.TestProto3}
 */
proto.jspb.test.TestProto3.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setOptionalInt32(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setOptionalInt64(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setOptionalUint32(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setOptionalUint64(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readSint32());
      msg.setOptionalSint32(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readSint64());
      msg.setOptionalSint64(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readFixed32());
      msg.setOptionalFixed32(value);
      break;
    case 8:
      var value = /** @type {number} */ (reader.readFixed64());
      msg.setOptionalFixed64(value);
      break;
    case 9:
      var value = /** @type {number} */ (reader.readSfixed32());
      msg.setOptionalSfixed32(value);
      break;
    case 10:
      var value = /** @type {number} */ (reader.readSfixed64());
      msg.setOptionalSfixed64(value);
      break;
    case 11:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setOptionalFloat(value);
      break;
    case 12:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setOptionalDouble(value);
      break;
    case 13:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setOptionalBool(value);
      break;
    case 14:
      var value = /** @type {string} */ (reader.readString());
      msg.setOptionalString(value);
      break;
    case 15:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setOptionalBytes(value);
      break;
    case 19:
      var value = new proto.jspb.test.ForeignMessage;
      reader.readMessage(value,proto.jspb.test.ForeignMessage.deserializeBinaryFromReader);
      msg.setOptionalForeignMessage(value);
      break;
    case 22:
      var value = /** @type {!proto.jspb.test.Proto3Enum} */ (reader.readEnum());
      msg.setOptionalForeignEnum(value);
      break;
    case 31:
      var value = /** @type {!Array<number>} */ (reader.readPackedInt32());
      msg.setRepeatedInt32List(value);
      break;
    case 32:
      var value = /** @type {!Array<number>} */ (reader.readPackedInt64());
      msg.setRepeatedInt64List(value);
      break;
    case 33:
      var value = /** @type {!Array<number>} */ (reader.readPackedUint32());
      msg.setRepeatedUint32List(value);
      break;
    case 34:
      var value = /** @type {!Array<number>} */ (reader.readPackedUint64());
      msg.setRepeatedUint64List(value);
      break;
    case 35:
      var value = /** @type {!Array<number>} */ (reader.readPackedSint32());
      msg.setRepeatedSint32List(value);
      break;
    case 36:
      var value = /** @type {!Array<number>} */ (reader.readPackedSint64());
      msg.setRepeatedSint64List(value);
      break;
    case 37:
      var value = /** @type {!Array<number>} */ (reader.readPackedFixed32());
      msg.setRepeatedFixed32List(value);
      break;
    case 38:
      var value = /** @type {!Array<number>} */ (reader.readPackedFixed64());
      msg.setRepeatedFixed64List(value);
      break;
    case 39:
      var value = /** @type {!Array<number>} */ (reader.readPackedSfixed32());
      msg.setRepeatedSfixed32List(value);
      break;
    case 40:
      var value = /** @type {!Array<number>} */ (reader.readPackedSfixed64());
      msg.setRepeatedSfixed64List(value);
      break;
    case 41:
      var value = /** @type {!Array<number>} */ (reader.readPackedFloat());
      msg.setRepeatedFloatList(value);
      break;
    case 42:
      var value = /** @type {!Array<number>} */ (reader.readPackedDouble());
      msg.setRepeatedDoubleList(value);
      break;
    case 43:
      var value = /** @type {!Array<boolean>} */ (reader.readPackedBool());
      msg.setRepeatedBoolList(value);
      break;
    case 44:
      var value = /** @type {string} */ (reader.readString());
      msg.addRepeatedString(value);
      break;
    case 45:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.addRepeatedBytes(value);
      break;
    case 49:
      var value = new proto.jspb.test.ForeignMessage;
      reader.readMessage(value,proto.jspb.test.ForeignMessage.deserializeBinaryFromReader);
      msg.addRepeatedForeignMessage(value);
      break;
    case 52:
      var value = /** @type {!Array<!proto.jspb.test.Proto3Enum>} */ (reader.readPackedEnum());
      msg.setRepeatedForeignEnumList(value);
      break;
    case 111:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setOneofUint32(value);
      break;
    case 112:
      var value = new proto.jspb.test.ForeignMessage;
      reader.readMessage(value,proto.jspb.test.ForeignMessage.deserializeBinaryFromReader);
      msg.setOneofForeignMessage(value);
      break;
    case 113:
      var value = /** @type {string} */ (reader.readString());
      msg.setOneofString(value);
      break;
    case 114:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setOneofBytes(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.jspb.test.TestProto3.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.jspb.test.TestProto3.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.jspb.test.TestProto3} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jspb.test.TestProto3.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getOptionalInt32();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getOptionalInt64();
  if (f !== 0) {
    writer.writeInt64(
      2,
      f
    );
  }
  f = message.getOptionalUint32();
  if (f !== 0) {
    writer.writeUint32(
      3,
      f
    );
  }
  f = message.getOptionalUint64();
  if (f !== 0) {
    writer.writeUint64(
      4,
      f
    );
  }
  f = message.getOptionalSint32();
  if (f !== 0) {
    writer.writeSint32(
      5,
      f
    );
  }
  f = message.getOptionalSint64();
  if (f !== 0) {
    writer.writeSint64(
      6,
      f
    );
  }
  f = message.getOptionalFixed32();
  if (f !== 0) {
    writer.writeFixed32(
      7,
      f
    );
  }
  f = message.getOptionalFixed64();
  if (f !== 0) {
    writer.writeFixed64(
      8,
      f
    );
  }
  f = message.getOptionalSfixed32();
  if (f !== 0) {
    writer.writeSfixed32(
      9,
      f
    );
  }
  f = message.getOptionalSfixed64();
  if (f !== 0) {
    writer.writeSfixed64(
      10,
      f
    );
  }
  f = message.getOptionalFloat();
  if (f !== 0.0) {
    writer.writeFloat(
      11,
      f
    );
  }
  f = message.getOptionalDouble();
  if (f !== 0.0) {
    writer.writeDouble(
      12,
      f
    );
  }
  f = message.getOptionalBool();
  if (f) {
    writer.writeBool(
      13,
      f
    );
  }
  f = message.getOptionalString();
  if (f.length > 0) {
    writer.writeString(
      14,
      f
    );
  }
  f = message.getOptionalBytes_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      15,
      f
    );
  }
  f = message.getOptionalForeignMessage();
  if (f != null) {
    writer.writeMessage(
      19,
      f,
      proto.jspb.test.ForeignMessage.serializeBinaryToWriter
    );
  }
  f = message.getOptionalForeignEnum();
  if (f !== 0.0) {
    writer.writeEnum(
      22,
      f
    );
  }
  f = message.getRepeatedInt32List();
  if (f.length > 0) {
    writer.writePackedInt32(
      31,
      f
    );
  }
  f = message.getRepeatedInt64List();
  if (f.length > 0) {
    writer.writePackedInt64(
      32,
      f
    );
  }
  f = message.getRepeatedUint32List();
  if (f.length > 0) {
    writer.writePackedUint32(
      33,
      f
    );
  }
  f = message.getRepeatedUint64List();
  if (f.length > 0) {
    writer.writePackedUint64(
      34,
      f
    );
  }
  f = message.getRepeatedSint32List();
  if (f.length > 0) {
    writer.writePackedSint32(
      35,
      f
    );
  }
  f = message.getRepeatedSint64List();
  if (f.length > 0) {
    writer.writePackedSint64(
      36,
      f
    );
  }
  f = message.getRepeatedFixed32List();
  if (f.length > 0) {
    writer.writePackedFixed32(
      37,
      f
    );
  }
  f = message.getRepeatedFixed64List();
  if (f.length > 0) {
    writer.writePackedFixed64(
      38,
      f
    );
  }
  f = message.getRepeatedSfixed32List();
  if (f.length > 0) {
    writer.writePackedSfixed32(
      39,
      f
    );
  }
  f = message.getRepeatedSfixed64List();
  if (f.length > 0) {
    writer.writePackedSfixed64(
      40,
      f
    );
  }
  f = message.getRepeatedFloatList();
  if (f.length > 0) {
    writer.writePackedFloat(
      41,
      f
    );
  }
  f = message.getRepeatedDoubleList();
  if (f.length > 0) {
    writer.writePackedDouble(
      42,
      f
    );
  }
  f = message.getRepeatedBoolList();
  if (f.length > 0) {
    writer.writePackedBool(
      43,
      f
    );
  }
  f = message.getRepeatedStringList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      44,
      f
    );
  }
  f = message.getRepeatedBytesList_asU8();
  if (f.length > 0) {
    writer.writeRepeatedBytes(
      45,
      f
    );
  }
  f = message.getRepeatedForeignMessageList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      49,
      f,
      proto.jspb.test.ForeignMessage.serializeBinaryToWriter
    );
  }
  f = message.getRepeatedForeignEnumList();
  if (f.length > 0) {
    writer.writePackedEnum(
      52,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 111));
  if (f != null) {
    writer.writeUint32(
      111,
      f
    );
  }
  f = message.getOneofForeignMessage();
  if (f != null) {
    writer.writeMessage(
      112,
      f,
      proto.jspb.test.ForeignMessage.serializeBinaryToWriter
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 113));
  if (f != null) {
    writer.writeString(
      113,
      f
    );
  }
  f = /** @type {!(string|Uint8Array)} */ (jspb.Message.getField(message, 114));
  if (f != null) {
    writer.writeBytes(
      114,
      f
    );
  }
};


/**
 * optional int32 optional_int32 = 1;
 * @return {number}
 */
proto.jspb.test.TestProto3.prototype.getOptionalInt32 = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.jspb.test.TestProto3.prototype.setOptionalInt32 = function(value) {
  jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional int64 optional_int64 = 2;
 * @return {number}
 */
proto.jspb.test.TestProto3.prototype.getOptionalInt64 = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {number} value */
proto.jspb.test.TestProto3.prototype.setOptionalInt64 = function(value) {
  jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional uint32 optional_uint32 = 3;
 * @return {number}
 */
proto.jspb.test.TestProto3.prototype.getOptionalUint32 = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/** @param {number} value */
proto.jspb.test.TestProto3.prototype.setOptionalUint32 = function(value) {
  jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional uint64 optional_uint64 = 4;
 * @return {number}
 */
proto.jspb.test.TestProto3.prototype.getOptionalUint64 = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/** @param {number} value */
proto.jspb.test.TestProto3.prototype.setOptionalUint64 = function(value) {
  jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional sint32 optional_sint32 = 5;
 * @return {number}
 */
proto.jspb.test.TestProto3.prototype.getOptionalSint32 = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/** @param {number} value */
proto.jspb.test.TestProto3.prototype.setOptionalSint32 = function(value) {
  jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional sint64 optional_sint64 = 6;
 * @return {number}
 */
proto.jspb.test.TestProto3.prototype.getOptionalSint64 = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/** @param {number} value */
proto.jspb.test.TestProto3.prototype.setOptionalSint64 = function(value) {
  jspb.Message.setProto3IntField(this, 6, value);
};


/**
 * optional fixed32 optional_fixed32 = 7;
 * @return {number}
 */
proto.jspb.test.TestProto3.prototype.getOptionalFixed32 = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/** @param {number} value */
proto.jspb.test.TestProto3.prototype.setOptionalFixed32 = function(value) {
  jspb.Message.setProto3IntField(this, 7, value);
};


/**
 * optional fixed64 optional_fixed64 = 8;
 * @return {number}
 */
proto.jspb.test.TestProto3.prototype.getOptionalFixed64 = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 8, 0));
};


/** @param {number} value */
proto.jspb.test.TestProto3.prototype.setOptionalFixed64 = function(value) {
  jspb.Message.setProto3IntField(this, 8, value);
};


/**
 * optional sfixed32 optional_sfixed32 = 9;
 * @return {number}
 */
proto.jspb.test.TestProto3.prototype.getOptionalSfixed32 = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 9, 0));
};


/** @param {number} value */
proto.jspb.test.TestProto3.prototype.setOptionalSfixed32 = function(value) {
  jspb.Message.setProto3IntField(this, 9, value);
};


/**
 * optional sfixed64 optional_sfixed64 = 10;
 * @return {number}
 */
proto.jspb.test.TestProto3.prototype.getOptionalSfixed64 = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 10, 0));
};


/** @param {number} value */
proto.jspb.test.TestProto3.prototype.setOptionalSfixed64 = function(value) {
  jspb.Message.setProto3IntField(this, 10, value);
};


/**
 * optional float optional_float = 11;
 * @return {number}
 */
proto.jspb.test.TestProto3.prototype.getOptionalFloat = function() {
  return /** @type {number} */ (+jspb.Message.getFieldWithDefault(this, 11, 0.0));
};


/** @param {number} value */
proto.jspb.test.TestProto3.prototype.setOptionalFloat = function(value) {
  jspb.Message.setProto3FloatField(this, 11, value);
};


/**
 * optional double optional_double = 12;
 * @return {number}
 */
proto.jspb.test.TestProto3.prototype.getOptionalDouble = function() {
  return /** @type {number} */ (+jspb.Message.getFieldWithDefault(this, 12, 0.0));
};


/** @param {number} value */
proto.jspb.test.TestProto3.prototype.setOptionalDouble = function(value) {
  jspb.Message.setProto3FloatField(this, 12, value);
};


/**
 * optional bool optional_bool = 13;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.jspb.test.TestProto3.prototype.getOptionalBool = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 13, false));
};


/** @param {boolean} value */
proto.jspb.test.TestProto3.prototype.setOptionalBool = function(value) {
  jspb.Message.setProto3BooleanField(this, 13, value);
};


/**
 * optional string optional_string = 14;
 * @return {string}
 */
proto.jspb.test.TestProto3.prototype.getOptionalString = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 14, ""));
};


/** @param {string} value */
proto.jspb.test.TestProto3.prototype.setOptionalString = function(value) {
  jspb.Message.setProto3StringField(this, 14, value);
};


/**
 * optional bytes optional_bytes = 15;
 * @return {!(string|Uint8Array)}
 */
proto.jspb.test.TestProto3.prototype.getOptionalBytes = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 15, ""));
};


/**
 * optional bytes optional_bytes = 15;
 * This is a type-conversion wrapper around `getOptionalBytes()`
 * @return {string}
 */
proto.jspb.test.TestProto3.prototype.getOptionalBytes_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getOptionalBytes()));
};


/**
 * optional bytes optional_bytes = 15;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getOptionalBytes()`
 * @return {!Uint8Array}
 */
proto.jspb.test.TestProto3.prototype.getOptionalBytes_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getOptionalBytes()));
};


/** @param {!(string|Uint8Array)} value */
proto.jspb.test.TestProto3.prototype.setOptionalBytes = function(value) {
  jspb.Message.setProto3BytesField(this, 15, value);
};


/**
 * optional ForeignMessage optional_foreign_message = 19;
 * @return {?proto.jspb.test.ForeignMessage}
 */
proto.jspb.test.TestProto3.prototype.getOptionalForeignMessage = function() {
  return /** @type{?proto.jspb.test.ForeignMessage} */ (
    jspb.Message.getWrapperField(this, proto.jspb.test.ForeignMessage, 19));
};


/** @param {?proto.jspb.test.ForeignMessage|undefined} value */
proto.jspb.test.TestProto3.prototype.setOptionalForeignMessage = function(value) {
  jspb.Message.setWrapperField(this, 19, value);
};


proto.jspb.test.TestProto3.prototype.clearOptionalForeignMessage = function() {
  this.setOptionalForeignMessage(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.jspb.test.TestProto3.prototype.hasOptionalForeignMessage = function() {
  return jspb.Message.getField(this, 19) != null;
};


/**
 * optional Proto3Enum optional_foreign_enum = 22;
 * @return {!proto.jspb.test.Proto3Enum}
 */
proto.jspb.test.TestProto3.prototype.getOptionalForeignEnum = function() {
  return /** @type {!proto.jspb.test.Proto3Enum} */ (jspb.Message.getFieldWithDefault(this, 22, 0));
};


/** @param {!proto.jspb.test.Proto3Enum} value */
proto.jspb.test.TestProto3.prototype.setOptionalForeignEnum = function(value) {
  jspb.Message.setProto3EnumField(this, 22, value);
};


/**
 * repeated int32 repeated_int32 = 31;
 * @return {!Array<number>}
 */
proto.jspb.test.TestProto3.prototype.getRepeatedInt32List = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 31));
};


/** @param {!Array<number>} value */
proto.jspb.test.TestProto3.prototype.setRepeatedInt32List = function(value) {
  jspb.Message.setField(this, 31, value || []);
};


/**
 * @param {!number} value
 * @param {number=} opt_index
 */
proto.jspb.test.TestProto3.prototype.addRepeatedInt32 = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 31, value, opt_index);
};


proto.jspb.test.TestProto3.prototype.clearRepeatedInt32List = function() {
  this.setRepeatedInt32List([]);
};


/**
 * repeated int64 repeated_int64 = 32;
 * @return {!Array<number>}
 */
proto.jspb.test.TestProto3.prototype.getRepeatedInt64List = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 32));
};


/** @param {!Array<number>} value */
proto.jspb.test.TestProto3.prototype.setRepeatedInt64List = function(value) {
  jspb.Message.setField(this, 32, value || []);
};


/**
 * @param {!number} value
 * @param {number=} opt_index
 */
proto.jspb.test.TestProto3.prototype.addRepeatedInt64 = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 32, value, opt_index);
};


proto.jspb.test.TestProto3.prototype.clearRepeatedInt64List = function() {
  this.setRepeatedInt64List([]);
};


/**
 * repeated uint32 repeated_uint32 = 33;
 * @return {!Array<number>}
 */
proto.jspb.test.TestProto3.prototype.getRepeatedUint32List = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 33));
};


/** @param {!Array<number>} value */
proto.jspb.test.TestProto3.prototype.setRepeatedUint32List = function(value) {
  jspb.Message.setField(this, 33, value || []);
};


/**
 * @param {!number} value
 * @param {number=} opt_index
 */
proto.jspb.test.TestProto3.prototype.addRepeatedUint32 = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 33, value, opt_index);
};


proto.jspb.test.TestProto3.prototype.clearRepeatedUint32List = function() {
  this.setRepeatedUint32List([]);
};


/**
 * repeated uint64 repeated_uint64 = 34;
 * @return {!Array<number>}
 */
proto.jspb.test.TestProto3.prototype.getRepeatedUint64List = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 34));
};


/** @param {!Array<number>} value */
proto.jspb.test.TestProto3.prototype.setRepeatedUint64List = function(value) {
  jspb.Message.setField(this, 34, value || []);
};


/**
 * @param {!number} value
 * @param {number=} opt_index
 */
proto.jspb.test.TestProto3.prototype.addRepeatedUint64 = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 34, value, opt_index);
};


proto.jspb.test.TestProto3.prototype.clearRepeatedUint64List = function() {
  this.setRepeatedUint64List([]);
};


/**
 * repeated sint32 repeated_sint32 = 35;
 * @return {!Array<number>}
 */
proto.jspb.test.TestProto3.prototype.getRepeatedSint32List = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 35));
};


/** @param {!Array<number>} value */
proto.jspb.test.TestProto3.prototype.setRepeatedSint32List = function(value) {
  jspb.Message.setField(this, 35, value || []);
};


/**
 * @param {!number} value
 * @param {number=} opt_index
 */
proto.jspb.test.TestProto3.prototype.addRepeatedSint32 = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 35, value, opt_index);
};


proto.jspb.test.TestProto3.prototype.clearRepeatedSint32List = function() {
  this.setRepeatedSint32List([]);
};


/**
 * repeated sint64 repeated_sint64 = 36;
 * @return {!Array<number>}
 */
proto.jspb.test.TestProto3.prototype.getRepeatedSint64List = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 36));
};


/** @param {!Array<number>} value */
proto.jspb.test.TestProto3.prototype.setRepeatedSint64List = function(value) {
  jspb.Message.setField(this, 36, value || []);
};


/**
 * @param {!number} value
 * @param {number=} opt_index
 */
proto.jspb.test.TestProto3.prototype.addRepeatedSint64 = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 36, value, opt_index);
};


proto.jspb.test.TestProto3.prototype.clearRepeatedSint64List = function() {
  this.setRepeatedSint64List([]);
};


/**
 * repeated fixed32 repeated_fixed32 = 37;
 * @return {!Array<number>}
 */
proto.jspb.test.TestProto3.prototype.getRepeatedFixed32List = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 37));
};


/** @param {!Array<number>} value */
proto.jspb.test.TestProto3.prototype.setRepeatedFixed32List = function(value) {
  jspb.Message.setField(this, 37, value || []);
};


/**
 * @param {!number} value
 * @param {number=} opt_index
 */
proto.jspb.test.TestProto3.prototype.addRepeatedFixed32 = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 37, value, opt_index);
};


proto.jspb.test.TestProto3.prototype.clearRepeatedFixed32List = function() {
  this.setRepeatedFixed32List([]);
};


/**
 * repeated fixed64 repeated_fixed64 = 38;
 * @return {!Array<number>}
 */
proto.jspb.test.TestProto3.prototype.getRepeatedFixed64List = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 38));
};


/** @param {!Array<number>} value */
proto.jspb.test.TestProto3.prototype.setRepeatedFixed64List = function(value) {
  jspb.Message.setField(this, 38, value || []);
};


/**
 * @param {!number} value
 * @param {number=} opt_index
 */
proto.jspb.test.TestProto3.prototype.addRepeatedFixed64 = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 38, value, opt_index);
};


proto.jspb.test.TestProto3.prototype.clearRepeatedFixed64List = function() {
  this.setRepeatedFixed64List([]);
};


/**
 * repeated sfixed32 repeated_sfixed32 = 39;
 * @return {!Array<number>}
 */
proto.jspb.test.TestProto3.prototype.getRepeatedSfixed32List = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 39));
};


/** @param {!Array<number>} value */
proto.jspb.test.TestProto3.prototype.setRepeatedSfixed32List = function(value) {
  jspb.Message.setField(this, 39, value || []);
};


/**
 * @param {!number} value
 * @param {number=} opt_index
 */
proto.jspb.test.TestProto3.prototype.addRepeatedSfixed32 = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 39, value, opt_index);
};


proto.jspb.test.TestProto3.prototype.clearRepeatedSfixed32List = function() {
  this.setRepeatedSfixed32List([]);
};


/**
 * repeated sfixed64 repeated_sfixed64 = 40;
 * @return {!Array<number>}
 */
proto.jspb.test.TestProto3.prototype.getRepeatedSfixed64List = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 40));
};


/** @param {!Array<number>} value */
proto.jspb.test.TestProto3.prototype.setRepeatedSfixed64List = function(value) {
  jspb.Message.setField(this, 40, value || []);
};


/**
 * @param {!number} value
 * @param {number=} opt_index
 */
proto.jspb.test.TestProto3.prototype.addRepeatedSfixed64 = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 40, value, opt_index);
};


proto.jspb.test.TestProto3.prototype.clearRepeatedSfixed64List = function() {
  this.setRepeatedSfixed64List([]);
};


/**
 * repeated float repeated_float = 41;
 * @return {!Array<number>}
 */
proto.jspb.test.TestProto3.prototype.getRepeatedFloatList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedFloatingPointField(this, 41));
};


/** @param {!Array<number>} value */
proto.jspb.test.TestProto3.prototype.setRepeatedFloatList = function(value) {
  jspb.Message.setField(this, 41, value || []);
};


/**
 * @param {!number} value
 * @param {number=} opt_index
 */
proto.jspb.test.TestProto3.prototype.addRepeatedFloat = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 41, value, opt_index);
};


proto.jspb.test.TestProto3.prototype.clearRepeatedFloatList = function() {
  this.setRepeatedFloatList([]);
};


/**
 * repeated double repeated_double = 42;
 * @return {!Array<number>}
 */
proto.jspb.test.TestProto3.prototype.getRepeatedDoubleList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedFloatingPointField(this, 42));
};


/** @param {!Array<number>} value */
proto.jspb.test.TestProto3.prototype.setRepeatedDoubleList = function(value) {
  jspb.Message.setField(this, 42, value || []);
};


/**
 * @param {!number} value
 * @param {number=} opt_index
 */
proto.jspb.test.TestProto3.prototype.addRepeatedDouble = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 42, value, opt_index);
};


proto.jspb.test.TestProto3.prototype.clearRepeatedDoubleList = function() {
  this.setRepeatedDoubleList([]);
};


/**
 * repeated bool repeated_bool = 43;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {!Array<boolean>}
 */
proto.jspb.test.TestProto3.prototype.getRepeatedBoolList = function() {
  return /** @type {!Array<boolean>} */ (jspb.Message.getRepeatedField(this, 43));
};


/** @param {!Array<boolean>} value */
proto.jspb.test.TestProto3.prototype.setRepeatedBoolList = function(value) {
  jspb.Message.setField(this, 43, value || []);
};


/**
 * @param {!boolean} value
 * @param {number=} opt_index
 */
proto.jspb.test.TestProto3.prototype.addRepeatedBool = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 43, value, opt_index);
};


proto.jspb.test.TestProto3.prototype.clearRepeatedBoolList = function() {
  this.setRepeatedBoolList([]);
};


/**
 * repeated string repeated_string = 44;
 * @return {!Array<string>}
 */
proto.jspb.test.TestProto3.prototype.getRepeatedStringList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 44));
};


/** @param {!Array<string>} value */
proto.jspb.test.TestProto3.prototype.setRepeatedStringList = function(value) {
  jspb.Message.setField(this, 44, value || []);
};


/**
 * @param {!string} value
 * @param {number=} opt_index
 */
proto.jspb.test.TestProto3.prototype.addRepeatedString = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 44, value, opt_index);
};


proto.jspb.test.TestProto3.prototype.clearRepeatedStringList = function() {
  this.setRepeatedStringList([]);
};


/**
 * repeated bytes repeated_bytes = 45;
 * @return {!(Array<!Uint8Array>|Array<string>)}
 */
proto.jspb.test.TestProto3.prototype.getRepeatedBytesList = function() {
  return /** @type {!(Array<!Uint8Array>|Array<string>)} */ (jspb.Message.getRepeatedField(this, 45));
};


/**
 * repeated bytes repeated_bytes = 45;
 * This is a type-conversion wrapper around `getRepeatedBytesList()`
 * @return {!Array<string>}
 */
proto.jspb.test.TestProto3.prototype.getRepeatedBytesList_asB64 = function() {
  return /** @type {!Array<string>} */ (jspb.Message.bytesListAsB64(
      this.getRepeatedBytesList()));
};


/**
 * repeated bytes repeated_bytes = 45;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getRepeatedBytesList()`
 * @return {!Array<!Uint8Array>}
 */
proto.jspb.test.TestProto3.prototype.getRepeatedBytesList_asU8 = function() {
  return /** @type {!Array<!Uint8Array>} */ (jspb.Message.bytesListAsU8(
      this.getRepeatedBytesList()));
};


/** @param {!(Array<!Uint8Array>|Array<string>)} value */
proto.jspb.test.TestProto3.prototype.setRepeatedBytesList = function(value) {
  jspb.Message.setField(this, 45, value || []);
};


/**
 * @param {!(string|Uint8Array)} value
 * @param {number=} opt_index
 */
proto.jspb.test.TestProto3.prototype.addRepeatedBytes = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 45, value, opt_index);
};


proto.jspb.test.TestProto3.prototype.clearRepeatedBytesList = function() {
  this.setRepeatedBytesList([]);
};


/**
 * repeated ForeignMessage repeated_foreign_message = 49;
 * @return {!Array<!proto.jspb.test.ForeignMessage>}
 */
proto.jspb.test.TestProto3.prototype.getRepeatedForeignMessageList = function() {
  return /** @type{!Array<!proto.jspb.test.ForeignMessage>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.jspb.test.ForeignMessage, 49));
};


/** @param {!Array<!proto.jspb.test.ForeignMessage>} value */
proto.jspb.test.TestProto3.prototype.setRepeatedForeignMessageList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 49, value);
};


/**
 * @param {!proto.jspb.test.ForeignMessage=} opt_value
 * @param {number=} opt_index
 * @return {!proto.jspb.test.ForeignMessage}
 */
proto.jspb.test.TestProto3.prototype.addRepeatedForeignMessage = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 49, opt_value, proto.jspb.test.ForeignMessage, opt_index);
};


proto.jspb.test.TestProto3.prototype.clearRepeatedForeignMessageList = function() {
  this.setRepeatedForeignMessageList([]);
};


/**
 * repeated Proto3Enum repeated_foreign_enum = 52;
 * @return {!Array<!proto.jspb.test.Proto3Enum>}
 */
proto.jspb.test.TestProto3.prototype.getRepeatedForeignEnumList = function() {
  return /** @type {!Array<!proto.jspb.test.Proto3Enum>} */ (jspb.Message.getRepeatedField(this, 52));
};


/** @param {!Array<!proto.jspb.test.Proto3Enum>} value */
proto.jspb.test.TestProto3.prototype.setRepeatedForeignEnumList = function(value) {
  jspb.Message.setField(this, 52, value || []);
};


/**
 * @param {!proto.jspb.test.Proto3Enum} value
 * @param {number=} opt_index
 */
proto.jspb.test.TestProto3.prototype.addRepeatedForeignEnum = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 52, value, opt_index);
};


proto.jspb.test.TestProto3.prototype.clearRepeatedForeignEnumList = function() {
  this.setRepeatedForeignEnumList([]);
};


/**
 * optional uint32 oneof_uint32 = 111;
 * @return {number}
 */
proto.jspb.test.TestProto3.prototype.getOneofUint32 = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 111, 0));
};


/** @param {number} value */
proto.jspb.test.TestProto3.prototype.setOneofUint32 = function(value) {
  jspb.Message.setOneofField(this, 111, proto.jspb.test.TestProto3.oneofGroups_[0], value);
};


proto.jspb.test.TestProto3.prototype.clearOneofUint32 = function() {
  jspb.Message.setOneofField(this, 111, proto.jspb.test.TestProto3.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.jspb.test.TestProto3.prototype.hasOneofUint32 = function() {
  return jspb.Message.getField(this, 111) != null;
};


/**
 * optional ForeignMessage oneof_foreign_message = 112;
 * @return {?proto.jspb.test.ForeignMessage}
 */
proto.jspb.test.TestProto3.prototype.getOneofForeignMessage = function() {
  return /** @type{?proto.jspb.test.ForeignMessage} */ (
    jspb.Message.getWrapperField(this, proto.jspb.test.ForeignMessage, 112));
};


/** @param {?proto.jspb.test.ForeignMessage|undefined} value */
proto.jspb.test.TestProto3.prototype.setOneofForeignMessage = function(value) {
  jspb.Message.setOneofWrapperField(this, 112, proto.jspb.test.TestProto3.oneofGroups_[0], value);
};


proto.jspb.test.TestProto3.prototype.clearOneofForeignMessage = function() {
  this.setOneofForeignMessage(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.jspb.test.TestProto3.prototype.hasOneofForeignMessage = function() {
  return jspb.Message.getField(this, 112) != null;
};


/**
 * optional string oneof_string = 113;
 * @return {string}
 */
proto.jspb.test.TestProto3.prototype.getOneofString = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 113, ""));
};


/** @param {string} value */
proto.jspb.test.TestProto3.prototype.setOneofString = function(value) {
  jspb.Message.setOneofField(this, 113, proto.jspb.test.TestProto3.oneofGroups_[0], value);
};


proto.jspb.test.TestProto3.prototype.clearOneofString = function() {
  jspb.Message.setOneofField(this, 113, proto.jspb.test.TestProto3.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.jspb.test.TestProto3.prototype.hasOneofString = function() {
  return jspb.Message.getField(this, 113) != null;
};


/**
 * optional bytes oneof_bytes = 114;
 * @return {!(string|Uint8Array)}
 */
proto.jspb.test.TestProto3.prototype.getOneofBytes = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 114, ""));
};


/**
 * optional bytes oneof_bytes = 114;
 * This is a type-conversion wrapper around `getOneofBytes()`
 * @return {string}
 */
proto.jspb.test.TestProto3.prototype.getOneofBytes_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getOneofBytes()));
};


/**
 * optional bytes oneof_bytes = 114;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getOneofBytes()`
 * @return {!Uint8Array}
 */
proto.jspb.test.TestProto3.prototype.getOneofBytes_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getOneofBytes()));
};


/** @param {!(string|Uint8Array)} value */
proto.jspb.test.TestProto3.prototype.setOneofBytes = function(value) {
  jspb.Message.setOneofField(this, 114, proto.jspb.test.TestProto3.oneofGroups_[0], value);
};


proto.jspb.test.TestProto3.prototype.clearOneofBytes = function() {
  jspb.Message.setOneofField(this, 114, proto.jspb.test.TestProto3.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.jspb.test.TestProto3.prototype.hasOneofBytes = function() {
  return jspb.Message.getField(this, 114) != null;
};


/**
 * @enum {number}
 */
proto.jspb.test.Proto3Enum = {
  PROTO3_FOO: 0,
  PROTO3_BAR: 1,
  PROTO3_BAZ: 2,
  MSG_PROTO3_BAH: 3
};

